import { Roboto } from 'next/font/google'
import type { Metadata } from "next";
import "./globals.css";
import { StoreProvider } from './features/storeprovider';
import { Providers } from './providers';
import Navbar from './navbar';

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Bukscharis",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <StoreProvider>
        <Providers>
          <body className={`${roboto.className} dark:bg-rare`} >
            <Navbar/>
            {children}
          </body>
        </Providers>
      </StoreProvider>
    </html>
  );
}
